### ISSUE TITLE
Suggestion: Logger Stuff

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#11]
A Static Logger is a good idea however it currently uses System.out and System.err to print its messages. It could easily be reworked to just be a static wrapper for the java logger class and could even be configured easily by a user. It could also then easily print to a log file rather than the console or the console or both. When not in developer mode though it should print out to a log file so that a console window doesn't show up but you still get the log information.

**Comment by sriharshachilakapati** [comment]
Yeah it's a good idea. I will be doing it in 0.0.4a once I had a filesystem abstraction (both for internal resources and external files) in SilenceEngine. Thanks for suggesting it.

**Comment by sriharshachilakapati** [comment]
I have implemented the functionality to add more `PrintStream`s to the logger, enable or disable printing to the java console, and also to add new `FilePath`s to save the logs to an external file. The code needs to be documented, but I'm closing this issue now as documentation can be done anytime. I don't want to keep issues alive for a long time.
