### ISSUE TITLE
BUG: Blank String = crash

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#15]
`creditHeaderFont.drawString(batcher, "", 0, 0);` throws the exception 

`com.shc.silenceengine.graphics.opengl.GLException$InvalidOperation: The specified operation is not allowed in current state`

This only happens with a blank string. A normal string will work fine. If the string is empty it should just skip doing anything however it crashes instead. a null pointer is thrown as expected when the string value is null though.

**Comment by sriharshachilakapati** [comment]
I think I can just return that method on an empty string and that will fix this bug. Will make a test soon and commit it. Thanks for reporting.

**Comment by sriharshachilakapati** [comment]
I just pushed a commit 76a0879 fixing this bug. It was caused because I asked to render a TRIANGLE with no vertices specified. Thanks for pointing it out.
