### ISSUE TITLE
Suggestion: Remove TimeUtils.Unit and replace with java TimeUnit

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#17]
Java provides a `TimeUnit` class that can convert from one unit of time to another and as the `glfwGetTime()` method defaults to using seconds as its time it is relatively easy to implement. It also provides support for larger time units though they are not really needed. This moves most of the code from `TimeUtils` into a normal java class that and changes it from a more math class to a more wrapper type class.

**Comment by sriharshachilakapati** [comment]
I know that Java provides a `TimeUnit` class, but I wanted to roll out my own, because to make the API stay the same when ported to, say GWT or Android. I have that idea in the future. I heard that `TimeUnit` class is not supported in GWT. For this reason, I don't want to fix this.
