### ISSUE TITLE
bugs in FPSCamera class

### ISSUE THREAD

**Issue by Iwanmwn** [sriharshachilakapati/SilenceEngine#19]
sensivity is probably high;
moveUp method doesn't move up the camera, it moves somewhere backward.
there is no limit for rotation by Y axis: camera rotates higher than 360 degrees like a flying sphere. Is this feature must be there? Or I need to solve this problem somehow by myself?

**Comment by sriharshachilakapati** [comment]
This is definitely a bug. I was limiting the position's y-component instead of the x-rotation. Will fix that soon. Thanks for reporting.

**Comment by sriharshachilakapati** [comment]
@Iwanmwn 

Please try now. I have fixed that class. It now limits the angle instead of the position.
