### ISSUE TITLE
Suggestion: ability to override IEngine components

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#24]
This goes hand in hand with the suggested `preInit()` method but during the `preInit()` method or before SilenceEngine is initilized a way to override the different default components like the collision or sound engines.

**Comment by sriharshachilakapati** [comment]
You mean allowing the user to override the engine used? Like a custom implementation for audio graphics etc.,?

**Comment by ShadowLordAlpha** [comment]
yes

**Comment by sriharshachilakapati** [comment]
I'm closing this, just because I feel that this is not useful. If the user needs his own implementation, he can always write his own classes.
