### ISSUE TITLE
Drawstring fails with NullPointerException

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [sriharshachilakapati/SilenceEngine#27]
SilenceEngine.graphics.getGraphics2D().drawString("Sometext", Vector2.ZERO);

throws a NullPointerException for me. Not sure if I have to initialize anything before, but I cannot draw a String.

**Comment by sriharshachilakapati** [comment]
You have to set the font to draw before you draw anything. I could set a default font, but loading a font takes some time which makes it look hanged for a moment in the start.

**Comment by sriharshachilakapati** [comment]
To update the status, this will not happen now, as there is a default font. The default one is 16 pt Arial.
