### ISSUE TITLE
3d models and textures question/bug?

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#28]
are textures being properly drawn to 3d models because currently I am only able to get pure white models to show up and the OBJModelTest also looks like the only thing affecting it is the color lights and not its own texture. though i could just be doing it all wrong

**Comment by ShadowLordAlpha** [comment]
hm no it was me however it seems that not setting some or all of these values
````
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ni 1.000000
d 1.000000
illum 2
````
in the mtl file breaks textures appearing. They should probably default to a value that allows a texture to apear when not set in the mtl file though again that could also be me.

**Comment by sriharshachilakapati** [comment]
There is no map_kd in the material file?

**Comment by ShadowLordAlpha** [comment]
there is I left it out because it was already in the file the whole thing is
```
newmtl dirt
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ni 1.000000
d 1.000000
illum 2
map_Kd dirt.jpg
```

**Comment by sriharshachilakapati** [comment]
The ambient component `Ka` of the material is set to zero which means the object will not be visible when there is no light. This is the behaviour you get when rendering it in Blender, or whatever modelling tool you use.

**Comment by ShadowLordAlpha** [comment]
The object would have shown up black then when it was showing up white as if there was to much light like the default is 1 1 1 not 0 0 0. Also there was light in the scene as I am using a modified version of obj test.

**Comment by sriharshachilakapati** [comment]
This is sounding like a bug, I'll work on this issue. And I'm browsing your code on the repository you pushed 13 hours ago, you are setting the light to white? So the shader is adding the light color I think, making everything look white. This is a shader issue probably. Will look at that as soon as possible.

**Comment by ShadowLordAlpha** [comment]
ok im updateing the code now so that it produces the white terrain on Yirath (none of the extra material parts set other than texture)

**Comment by sriharshachilakapati** [comment]
And does the model has texture coordinates exported? Otherwise the model assumes the texture coordinate as zeroes, so the texture might be rendered gray or white.

**Comment by ShadowLordAlpha** [comment]
no texture coordinates are correct (the exporter i use will only export a mtl file when it has a texture so it will also generate the proper coords) just adding this
```
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ni 1.000000
d 1.000000
illum 2
```
between `newmtl dirt` and `map_Kd dirt.jpg` will fix it to display properly as well

**Comment by sriharshachilakapati** [comment]
Did it fix this issue? I'll have to re-implement the model class anyway to support animated models, so if this isn't fixed, I will look at this too. The shaders are looking correct to me. If you confirm that this is working, I will close this issue.

**Comment by ShadowLordAlpha** [comment]
setting it directly does fix the problem however in the `Material` class your default for ambient is `ambient = new Color(1, 1, 1, 1);` when it should more likely be black or something like `ambient = new Color(0.1f, 0.1f, 0.1f, 1);`

**Comment by sriharshachilakapati** [comment]
I set the default ambient to white, because the `Material` is also applied to the 2D rendering, made through `Batcher`. The model changes the material, does the rendering, and switches back to the default material so that the GUI and other 2D graphics will render at full intensity. And, many models will set those values in their models, so there is no need to change that.

I'm now closing this issue, but you can still reply to it if you want to say something on this topic.
