### ISSUE TITLE
Possible bug with ResourceLoader

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#29]
The `ResourceLoader` resets all the other window states back to how they were however it does not reset the clear color back to what it was before it was run. This isn't a big problem however the color that the scene should be must be reset after every time the loader is run then

**Comment by sriharshachilakapati** [comment]
Will fix it as soon as I could. Thanks for reporting.

**Comment by sriharshachilakapati** [comment]
This is now fixed. Now the `GraphicsEngine` stores the clear color, and sets it every frame when changed. You can set the clear color from both `SilenceEngine.graphics.setClearColor(Color)` and also `GL3Context.clearColor(Color)` methods, but it is preferred to use the `GraphicsEngine`.
