### ISSUE TITLE
Suggestion: Entity3DScale

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#31]
You have ways of setting the Scale in the `Transform` class however there is no way to set a `Entity3D`'s scale. Using the `Transform` matrix its possable to render a `Model` at the scale you wish however there is no method to pass a `Transform` into a `Entity3D` nor is there a way to scale is built in to the class like `Entity3D.scale(sx, sy, sz);` or `Entity3D.scale(s);` Though it is possable to force a scale by modifing the local transform or setting a default parent and scaling that (not tested . . . yet)

**Comment by sriharshachilakapati** [comment]
This is, well postponed for now, as the Entity3D class will be rewritten when the scene graph changed.

**Comment by ShadowLordAlpha** [comment]
not a problem just something to remember

**Comment by sriharshachilakapati** [comment]
I have implemented the scale method for both Entity3D class and also the Polyhedron class. These are now working, so I'm closing this issue.
