### ISSUE TITLE
Getting rid of AWT dependency

### ISSUE THREAD

**Issue by sriharshachilakapati** [sriharshachilakapati/SilenceEngine#32]
Right now, we are depending on AWT to load textures and also fonts, and since LWJGL3 doesn't support AWT integration, we are doing it in a hacky way. With the latest build, LWJGL3 has got bindings to the [STB](https://github.com/nothings/stb) library, we could use it to get rid of AWT, and also other dependencies other than LWJGL itself. Here is a list of what we could change.

  - [x] The textures. Right now, we are using ImageIO to load the textures. We can use `STBImage` now.
  - [ ] The fonts. Right now, we are using java's Font class. We can now use `STBTruetype` now.
  - [x] OGG decoding. Right now, we are using J-Ogg and J-Orbis combined. Now we can use `STBVorbis` class to do that.

However, we can't completely get rid of AWT, as we still might need to use it to load WAV, MIDI, AIFF and AU audio files, which STB doesn't support. I think this is a better enhancement, because at least, the number of JAR files we have to distribute decreases. However, this will be only done once issue #30 is done.

**Comment by ShadowLordAlpha** [comment]
not a bad idea as AWT is very old and slow for the most part but even if its not used for removing the image loading just removing two other libraries/dependencies is a decent thing and most people can deal with only one sound type file (or write/find their own if you give them a way to do that)

**Comment by ShadowLordAlpha** [comment]
Also just a side note that we may need to use AWT as a fallback due to not all versions of the supported image formats being supported (like png 16 bit i think was one of them)

**Comment by sriharshachilakapati** [comment]
I have got rid of the J-OGG and J-Orbis libraries, and now the OggReader uses the STBVorbis class. The next change will be in textures.

> Also just a side note that we may need to use AWT as a fallback due to not all versions of the supported image formats being supported (like png 16 bit i think was one of them)

We do need AWT for reading WAV, MIDI and AIFF files, but not for PNG images. I don't think 16-bit PNGs are in use today, most use 24-bit PNGs.

**Comment by sriharshachilakapati** [comment]
I'm closing this issue for now, since STBTrueType must need TTF data file and not the family name, it cannot load the font from the system. Will reopen this when I find a solution to this issue.
