### ISSUE TITLE
JOML Math Library

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#36]
Ok so while i know that we already have a custom coded math/util type library it might be a good idea to possibly change to [JOML](https://github.com/JOML-CI/JOML) as it was the suggested math library from the [LWJGL Blog](http://blog.lwjgl.org/maths-library/) though this library seems to be getting a large number of updates and has had several fixes/updates over the last few weeks though the core seems to be mostly static

**Comment by sriharshachilakapati** [comment]
I think that will break a lot of code that is working right now, the design is entirely different. JOML aims to be allocation free, while that is a good goal for a math library, it doesn't support chaining of operations. I'm not saying that it is bad or something, it's really good, but in this specific case, I prefer my own math classes, at least for this engine.
