### ISSUE TITLE
TMX Tiled Map Editor Support

### ISSUE THREAD

**Issue by sriharshachilakapati** [sriharshachilakapati/SilenceEngine#37]
Title says it all, this issue is used as a tracker for adding the TMX Tiled Map Editor Support to SilenceEngine. This will be a big feature as it allows for easy editing of tile maps. The maps will be loaded as just data, and Scene2D will be created from the map.

Here is a list of what works and what does not.

  - [x] Rendering of TmxImageLayer
  - [x] Rendering of TmxTileLayer
  - [x] Transparency and blending between layers
  - [x] Tiles from multiple tilesets
  - [x] Tile Flipping
  - [x] Rendering of animated tiles
  - [ ] ~~Support for TMX rendering order (Uses RIGHT_DOWN which is default)~~
  - [x] Isometric maps
  - [ ] ~~Isometric (Staggered) maps~~
  - [ ] ~~Hexagonal (Staggered) maps~~

**Comment by cebarks** [comment]
Hey, there is already a java library written by the author of Tiled which is BSD licensed: https://github.com/bjorn/tiled/tree/master/util/java/libtiled-java

**Comment by sriharshachilakapati** [comment]
@cebarks 

Thanks for your reply, but I have seen it before. This library is based on Tiled Java (the original Tiled editor written in Java using swing). Since then, they have switched to C++ and Qt toolkit. And more recently, there are also some changes in the file format.

So maybe I will write my own parser, looking at the documentation of Tiled file format as it is documented on their documentation website. You can read it there, see [TMX Map Format - Tiled Documentation](http://doc.mapeditor.org/reference/tmx-map-format/).

**Comment by ShadowLordAlpha** [comment]
Its XML based so it shouldn't be to hard to write a parser and just have their editor be referenced as something Silence can use

**Comment by sriharshachilakapati** [comment]
The issue right now is how to transform tiles in the tilesets into sprites, and create entities from object layers. But first, I think we should be writing the base structure classes and load the maps as data. I will start working on it soon.

**Comment by ShadowLordAlpha** [comment]
for the most part it seems like you would simply use the image and tile attributes of the tileset. There also seems to be some editing information stored in those sets as well like probability so those values can be ignored. Using something like a hashmap <Integer, image> would probably work as I am assuming all the tiles that the map needs are in its sprite sheet you just need to access them properly and store their ID so they can be used when the map data is read

**Comment by sriharshachilakapati** [comment]
As I'm finding the documentation really hard to understand correctly (why is there a `<tile>` element two times described twice in the docs?). So I googled and found this project:

https://github.com/andrewrk/tmxparser

That project is being updated lately (last updated 19 days ago) and is latest, but is in C++. I think I will be porting it to Java in SilenceEngine.

**Comment by cebarks** [comment]
I wrote a super simple parser for it a while ago. I've since lost my source code (back before I knew about got and github), maybe I might be able to help you out!

**Comment by sriharshachilakapati** [comment]
Thanks a lot @cebarks, I might need some help on this. I have ported most of the classes, and only 10 more classes are left, so I will try to commit it very soon, later tonight or tomorrow morning maybe.

However, I still do not understand how to do the rendering, as this parser will just parse the XML file and provide an easy to use object oriented structures. I know how to render tile and image layers, but somehow we have to create Entity's from the object layers.

**Comment by sriharshachilakapati** [comment]
I have successfully ported the parser to Java, and it is working pretty fine. All we need to do now is to write a map renderer. See the `TmxMapTest` to see the API in action.

**Comment by sriharshachilakapati** [comment]
I finally managed to get the test TMX map (orthogonal) working and rendered using the batcher.

![TMX Map in action](http://i.imgur.com/xug18Li.png)

I will commit this early tomorrow after some refactorings. Unfortunately, there is no support till now for animated tiles, which can be added easily in my opinion. Here is a list of what works and what does not.

  - [x] Rendering of TmxImageLayer
  - [x] Rendering of TmxTileLayer
  - [x] Transparency and blending between layers
  - [x] Tiles from multiple tilesets
  - [ ] Rendering of animated tiles
  - [ ] Support for TMX rendering order (Uses RIGHT_DOWN which is default)
  - [ ] Isometric maps
  - [ ] Isometric (Staggered) maps
  - [ ] Hexagonal (Staggered) maps

And one more thing, the renderer does not render objects, as the main use of objects is to denote collision areas and entity spawn points. That is left as the responsibility of the user (developer) to read the object layer data and create the entities.

**Comment by ShadowLordAlpha** [comment]
To support the different TMX rendering formats you could simply reorder the data to an internal format that then sends that reordered data to the renderer

**Comment by sriharshachilakapati** [comment]
Having an internal format is not a bad idea, but I prefer to keep the renderers separate. My idea is there should be different renderers, and a renderer should extend from the `TmxMapRenderer` class.

```java
public static TmxMapRenderer create(TmxMap map)
{
    switch (map.getOrientation())
    {
        case ORTHOGONAL: return new TmxOrthogonalMapRenderer(map);
        case ISOMETRIC:  return new TmxIsometricMapRenderer(map);
        ...
    }

    throw new SilenceException("A renderer for orientation " + map.getOrientation()
                                    + " has not been implemented yet");
}
```

In that way, it should be easy to create the renderer I think. That is because the tile shape differs between orthogonal, isometric, staggered and hexagonal maps.

**Comment by ShadowLordAlpha** [comment]
True the shape of the tile differs however the basic way its rendered should be basically the same though all the maps. If you can take that and generalize it then it would be easy to then take that renderer and use if for other formats besides it being made just for TMX.

**Comment by sriharshachilakapati** [comment]
The `TmxIsometricMapRenderer` now actually works, it does it's rendering by converting the isometric tile coordinates to orthographic coordinates.

![Isometric example map](http://i.imgur.com/WDGNwQH.png)

The lines appear due to the tiles not being in perfect shape, as I have downloaded them online and trimmed them a bit in GIMP, they appear the same in the editor too.

**Comment by sriharshachilakapati** [comment]
SilenceEngine now supports rendering of animated tiles in both Orthogonal and Isometric map renderers. Here is a small GIF showing it.

![Animated Tiles](http://i.imgur.com/eQLJyvT.gif)

It is still the responsibility of the user to read the object layers themselves and add the entities to the scene. That will be like this:

```java
for (TmxObjectLayer objectLayer : map.getObjectLayers())
{
    for (TmxObject object : objectLayer.getObjects())
    {
        // Find the correct java entity class by checking object.name or object.type
        // Create a polygon from the vertices defined in object.polygon
        // Create the entity with a sprite and the polygon, add it to the scene
        // Set the position of the entity to [object.x, object.y]
    }
}
```

Closing this issue now as most of the things planned are now done and the rest of the features are not useful for most games anyway. Feel free to reopen this if you need staggered renderers.
