### ISSUE TITLE
MathUtils.fract should be the 'real' fractional part

### ISSUE THREAD

**Issue by httpdigest** [sriharshachilakapati/SilenceEngine#40]
Hi,
I have just seen in your MathUtils class that the method [fract()](https://github.com/sriharshachilakapati/SilenceEngine/blob/master/src/main/java/com/shc/silenceengine/utils/MathUtils.java#L307) does not return what is the common understanding of the "decimal fractional part".

It instead returns the fractional part interpreted as an integer, which also depends on the formatting that the JVM uses to print that value, since you convert it to string and truncate everything before the decimal point.

Usually, the fractional part of a decimal number is the same decimal number except with a zero before the decimal separator.
So 1.523 becomes 0.523 and 235.10 becomes 0.1.

Why is that so?
Because the fractional part is usually being used in operations that require modulo arithmetics, such as with noise functions, where you want repeating fractional values over a lattice of integer values.

I propose therefore to implement that method either via `x % 1.0` or `x - (int)x`.
This will also allow you to keep the sign of `x`in the result, since negative values will be preserved.

**Comment by sriharshachilakapati** [comment]
Ah I forgot about that totally, it was written by copying the documentation of the frac function of game maker in GML, and though I think I interpreted it wrong:

> `frac()` returns the decimal fraction of a number, in other words, the part past the decimal point.

I never found this since I never used this myself in any game. Thanks for spotting it out. I will fix that right now.
