### ISSUE TITLE
Inverted Normals using PointLight

### ISSUE THREAD

**Issue by EternalCode0** [sriharshachilakapati/SilenceEngine#43]
The normals when lighting the 3D cube example posted [here](http://silenceengine.goharsha.com/forum/general-discussion/checklist/) are inverted for the left, top, and back faces.

![Error in Lighting](http://i.gyazo.com/d65bb477e9bec02dda75dd520cc2ecc5.png)

**Comment by sriharshachilakapati** [comment]
The issue here is the winding order of the generated vertices of the cube faces. The vertices of the top, left and front faces are specified in clock wise order, while the others are specified in counter clock wise order. Fixing that got me the correct results now.
