### ISSUE TITLE
Use a common logging framework

### ISSUE THREAD

**Issue by EternalCode0** [sriharshachilakapati/SilenceEngine#44]
Instead of using SilenceEngine's built in Logger, it may be better to use a popular logging framework. Otherwise people who want to use a logging framework will either use it, thus making 2 different logging systems being used in the same project, or will have to use a SilenceEngine's younger and incomplete version.

The most common logging systems I know of are SLF4J, Log4J, and Logback.

**Comment by ShadowLordAlpha** [comment]
It should be relatively simple to convert the current system over to one of the frameworks though it would also be decently simple to just include the jar in the system. The current logging method doesn't use any developed logger just a print stream really if i remember correctly.

**Comment by sriharshachilakapati** [comment]
Instead of switching the logging framework, I'm more interested in improving the existing logger for two reasons.

  1. The current logger works just fine, and also logs at multiple levels.
  2. Having a single logger is better because it is easy to log messages on the other logger if there are any.

Having said this, one more thing that is bugging me is the addition of two or more dependency JARs. For example, you need `slf4j-api` and `slf4j-simple` jars to get SLF4J working.

**Comment by ShadowLordAlpha** [comment]
1. Yes it works fine however it is lacking in features that other logging frameworks and solutions give the end user and nearly every logging framework logs at multiple levels. Even the basic Java logger does that and technically more than the current logger does though I have no wish to go into details about it .

2. The logger you have is in essence a static wrapping of a logger and can be easily exchanged with something like `SilenceEngine.getStaticLogger()` however as you do not actually wrap a logging framework and instead created your own. while this gives you far more control over the logger itself it also causes you to need to upkeep the logger, fix bugs, add features, remove things, make it go faster, ect. Using a third party one is fine and removes the need for all those things

Technically if you release as a jar it would only add one as the api can be used without a logger implementation component and it will default to NOP bindings and for all the flexibility it gives adding one jar with 3 packages and 24 classes should be fine

**Comment by sriharshachilakapati** [comment]
To be frank, I'm not at all interested in making this change, I still feel that this is not at all necessary, I will get enough control with my own implementation. What I want to say is, I don't want to make using SLF4J or any other logging library mandatory to use SilenceEngine, but instead, I want to leave it to the user to chose which logging framework he wants to use.

Do we have any other ways to redirecting the logs? I'm thinking of allowing the user to set a callback that gets the strings, and the user can do what ever he wants to do with them. He might then use the default callbacks that print to the console, or redirect them into the logging framework of his choice.

Even now, I do feel that logging has very little to help in games, I've only seen loggers used widely in server applications, and client side logs I have seen are simple dumps of text data, probably very very small, either in files or simply in the console. To find bugs, we no more use loggers, but we have more powerful debuggers are profilers. My real question is, is it really important to use a logging framework, even when what we have right now is enough?

**Comment by EternalCode0** [comment]
Personally, I plan to make a multiplayer game with SilenceEngine so a logger for the console would be very handy. On top of that the game I plan to make is meant to serve as an introduction to game programming for other people. It will allow users to add their own features in game, thus a fully developed logger would be nice.

**Comment by sriharshachilakapati** [comment]
I think you should be fine with using your own logging system along with the default logger. I'll try to add a log redirection mechanism via callbacks, so you can redirect the logs into your preferred logging framework. Could you give me a short example (through code) on how you would like to use the logger?

**Comment by EternalCode0** [comment]
I can't agree that using two different logging systems in the same project is a good idea. If you are that opposed to it then I would rather help contribute to the current logging system.

**Comment by TheOnlySilverClaw** [comment]
I think using two separate logging systems for client and server is not that bad and agree with SHC, most games really do not need a complete logging framework. And if so, they can just use that instead.

**Comment by sriharshachilakapati** [comment]
I think there is some misunderstanding, did I sound like that? I just simply didn't want to make a dependency that is mandatory, like, what if the user doesn't need to log anything? What if he is just doing a simple game? That would be just excess number of useless dependencies. But they must be in the classpath, even if the user didn't use, because the engine uses it.

By a redirection system, the default logger will not function when the redirection is active, so there will be only one logging system functional in the end. The default logger class will then simply pass the logged messages to you via the callbacks.

And one more thing, you will not be writing the server using SilenceEngine, that is a completely separate application running on the server. SilenceEngine only does the client side stuff, collision detection, rendering with OpenGL etc.,

**Comment by EternalCode0** [comment]
If the user didn't need to log anything in the first place then SilenceEngine's built-in logger would be worthless to him too, I see that your saying it's one less dependency to work with and therefore less of a file size, but in the end SilenceEngine may eventually have a logging system just as big on it's own.

I understand that you want to use a redirection system, but (correct me if I'm wrong) that's still SilenceEngine's logging framework and another logging framework being used, thus this is now essentially the same thing as the user that doesn't use a logging system, there's a part of SilenceEngine that is only being the middleman for log messages which will only reduce performance compared to when a single logging framework.

**Comment by EternalCode0** [comment]
Personally I cannot see how using two separate logging frameworks can be good for a project. If you or anyone else thinks otherwise, please explain how.

**Comment by sriharshachilakapati** [comment]
Let me clarify one thing first, when redirection is enabled, the Logger will not give any output at all, it just passes it's arguments to the callbacks. This just works like SLF4J works, just passing the log statements to the underlying log framework. So I think there will be no overhead as this is the same that SLF4J does too.

And then, even if the user doesn't use any logging system at all, having a single unused class is better than a complete unused library. And the engine itself will use the default logger all the time. So if redirection is enabled, the engine uses the target library through the Logger redirection. So it is just that only one logging framework is in use.

**Comment by httpdigest** [comment]
Hi Sri!
Interesting talks here. :)
Let me get that straight: In essence you are doing the exact same thing that the simple logging facade is already doing with the only reason being that you don't want to include an additional compiletime and runtime dependency of slf4j's API to SilenceEngine.
Maybe try to set aside the possible drawbacks of adding a commonly known logging facade library for a moment, and concentrate on the gains this would bring: the major gain is that people are far more likely to know and be comfortable with slf4j than with your own logger and can easily configure the logging produced by SilenceEngine via their own backend logging framework (JDK logger, log4j, ...) using their own appenders and filters. Using the simple logging facade people would not need to adapt to your own logging API by implementing some callback interface.
They could just straight away use JDK logger or log4j or any other backend for slf4j with SilenceEngine without having to write a single line of code. slf4j would just pick up an available backend from the classpath or via some configuration file.
I just want to point out the drawbacks that people would get when having to interface with your own logging framework.

**Comment by sriharshachilakapati** [comment]
The Logger in SilenceEngine is just a utility class, and is only used to log the info statements while the engine is starting and shutting off. I don't believe that SilenceEngine will do more than that amount of logging, at least in the near future, making there is no need for a complete logging framework to be a dependancy of the engine. I will review SLF4J in future if I feel that there is a need for this.

However, to help the users who would like to use SLF4J or any other logging framework in their own game, I will be adding a simple callback based redirecting mechanism as I have already stated. I'm now closing this issue, but if you have any other points to say, you can still do so.
