### ISSUE TITLE
Display data not being updated immediately?

### ISSUE THREAD

**Issue by darkhax** [sriharshachilakapati/SilenceEngine#51]
This is probably more of an issue on my end, however I have been having trouble getting the size of the display to update correctly. I am setting the size of the display in the start of the init call, however it starts off small, and then updates it's size after a second or two. 
![animation](https://cloud.githubusercontent.com/assets/2250798/11320446/45d533ee-9055-11e5-9160-a3451c249804.gif)

I was having a similar issue with the window title being updated, however once I moved the title update to the main run method, before I start the game, it updates correctly. The size does not seem to update at all if I do that to the window size however. 

```java
public static void main (String[] args) {
        
    Display.setTitle("Silence Engine: Darkhax's Test Game");
    Game.DEVELOPMENT = false;
        
    new Core().start();
}
    
@Override
public void init () {
        
    Display.setSize(1280, 720);
    DeckHandler.initDeck();
    Resources.init();
}
    
@Override
public void update (float delta) {
    
}
    
@Override
public void render (float delta, Batcher batcher) {
    
}
    
@Override
public void resize () {
    
}
    
@Override
public void dispose () {
    
}
```

**Comment by sriharshachilakapati** [comment]
You can use the `preInit()` method to set the size before. This happens because the init method is called after the engine itself is started, so it will change the size after the init method is called.

```java
@Override
public void preInit()
{
    Display.setSize(1280, 720);
}
```

The preInit will be called before creating the OpenGL context, since display will not be created by then. So it will be created with the size you specified here.
