### ISSUE TITLE
Can't compile on Windows 10 with JDK 8

### ISSUE THREAD

**Issue by wb9688** [sriharshachilakapati/SilenceEngine#52]
I can't compile on Windows 10 with JDK 8...

**Comment by sriharshachilakapati** [comment]
Please give me more details on what is not working. Without more details, I can't help.

**Comment by wb9688** [comment]
I got the following error:

C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\Grid.java:178: error: ')' expected
            list.forEach(this::insert);
                             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\Grid.java:178: error: illegal start of expression
            list.forEach(this::insert);
                              ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\Grid.java:178: error: ';' expected
            list.forEach(this::insert);
                                     ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: illegal start of type
        default List<Entity2D> retrieve(Entity2D e)
        ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: = expected
        default List<Entity2D> retrieve(Entity2D e)
                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: ';' expected
        default List<Entity2D> retrieve(Entity2D e)
                    ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: <identifier> expected
        default List<Entity2D> retrieve(Entity2D e)
                             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: ';' expected
        default List<Entity2D> retrieve(Entity2D e)
                              ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: illegal start of type
        default List<Entity2D> retrieve(Entity2D e)
                                       ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: = expected
        default List<Entity2D> retrieve(Entity2D e)
                                                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: illegal start of type
        default List<Entity2D> retrieve(Entity2D e)
                                                  ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:43: error: <identifier> expected
        default List<Entity2D> retrieve(Entity2D e)
                                                   ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:45: error: = expected
            return retrieve(e.getBounds());
            ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:45: error: ';' expected
            return retrieve(e.getBounds());
                  ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:45: error: illegal start of type
            return retrieve(e.getBounds());
                           ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:45: error: = expected
            return retrieve(e.getBounds());
                             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:45: error: <identifier> expected
            return retrieve(e.getBounds());
                                       ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:45: error: ';' expected
            return retrieve(e.getBounds());
                                         ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:48: error: class, interface, or enum expected
        List<Entity2D> retrieve(Rectangle rect);
        ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase2D.java:49: error: class, interface, or enum expected
    }
    ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: illegal start of type
        default List<Entity3D> retrieve(Entity3D e)
        ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: = expected
        default List<Entity3D> retrieve(Entity3D e)
                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: ';' expected
        default List<Entity3D> retrieve(Entity3D e)
                    ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: <identifier> expected
        default List<Entity3D> retrieve(Entity3D e)
                             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: ';' expected
        default List<Entity3D> retrieve(Entity3D e)
                              ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: illegal start of type
        default List<Entity3D> retrieve(Entity3D e)
                                       ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: = expected
        default List<Entity3D> retrieve(Entity3D e)
                                                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: illegal start of type
        default List<Entity3D> retrieve(Entity3D e)
                                                  ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:43: error: <identifier> expected
        default List<Entity3D> retrieve(Entity3D e)
                                                   ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:45: error: = expected
            return retrieve(e.getBounds());
            ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:45: error: ';' expected
            return retrieve(e.getBounds());
                  ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:45: error: illegal start of type
            return retrieve(e.getBounds());
                           ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:45: error: = expected
            return retrieve(e.getBounds());
                             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:45: error: <identifier> expected
            return retrieve(e.getBounds());
                                       ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:45: error: ';' expected
            return retrieve(e.getBounds());
                                         ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:48: error: class, interface, or enum expected
        List<Entity3D> retrieve(Polyhedron rect);
        ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\IBroadphase3D.java:49: error: class, interface, or enum expected
    }
    ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\QuadTree.java:245: error: ')' expected
            entities.forEach(this::insert);
                                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\QuadTree.java:245: error: illegal start of expression
            entities.forEach(this::insert);
                                  ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\broadphase\QuadTree.java:245: error: ';' expected
            entities.forEach(this::insert);
                                         ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:153: error: ')' expected
                entities.stream().filter(class1::isInstance).forEach(entity ->
                                               ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:153: error: illegal start of expression
                entities.stream().filter(class1::isInstance).forEach(entity ->
                                                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:153: error: ';' expected
                entities.stream().filter(class1::isInstance).forEach(entity ->
                                                           ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:153: error: illegal start of expression
                entities.stream().filter(class1::isInstance).forEach(entity ->
                                                                             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:154: error: illegal start of expression
                {
                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:154: error: ';' expected
                {
                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:155: error: illegal start of expression
                    List<Entity2D> collidables = broadphase.retrieve(entity);
                                   ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:155: error: illegal start of expression
                    List<Entity2D> collidables = broadphase.retrieve(entity);
                                               ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:155: error: ';' expected
                    List<Entity2D> collidables = broadphase.retrieve(entity);
                                                           ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:163: error: illegal start of expression
                                .filter(class2 -> class2.isInstance(entity2) && entity != entity2)
                                                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:165: error: illegal start of expression
                                .filter(class2 -> entity.getPolygon().intersects(entity2.getPolygon()))
                                                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:167: error: illegal start of expression
                                .forEach(class2 -> entity.collision(entity2));
                                                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:168: error: illegal start of type
                });
                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider2D.java:170: error: class, interface, or enum expected
    }
    ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:151: error: ')' expected
                entities.stream().filter(class1::isInstance).forEach(entity ->
                                               ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:151: error: illegal start of expression
                entities.stream().filter(class1::isInstance).forEach(entity ->
                                                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:151: error: ';' expected
                entities.stream().filter(class1::isInstance).forEach(entity ->
                                                           ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:151: error: illegal start of expression
                entities.stream().filter(class1::isInstance).forEach(entity ->
                                                                             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:152: error: illegal start of expression
                {
                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:152: error: ';' expected
                {
                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:153: error: illegal start of expression
                    List<Entity3D> collidables = broadphase.retrieve(entity);
                                   ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:153: error: illegal start of expression
                    List<Entity3D> collidables = broadphase.retrieve(entity);
                                               ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:153: error: ';' expected
                    List<Entity3D> collidables = broadphase.retrieve(entity);
                                                           ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:161: error: illegal start of expression
                                .filter(class2 -> class2.isInstance(entity2) && entity != entity2)
                                                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:163: error: illegal start of expression
                                .filter(class2 -> entity.getPolyhedron().intersects(entity2.getPolyhedron()))
                                                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:165: error: illegal start of expression
                                .forEach(class2 -> entity.collision(entity2));
                                                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:166: error: illegal start of type
                });
                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\collision\colliders\SceneCollider3D.java:168: error: class, interface, or enum expected
    }
    ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Display.java:183: error: ')' expected
                window.setSizeCallback(Display::glfwSizeCallback);
                                              ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Display.java:183: error: illegal start of expression
                window.setSizeCallback(Display::glfwSizeCallback);
                                               ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Display.java:183: error: ';' expected
                window.setSizeCallback(Display::glfwSizeCallback);
                                                                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Display.java:184: error: ')' expected
                window.setPositionCallback(Display::glfwPositionCallback);
                                                  ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Display.java:184: error: illegal start of expression
                window.setPositionCallback(Display::glfwPositionCallback);
                                                   ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Display.java:184: error: ';' expected
                window.setPositionCallback(Display::glfwPositionCallback);
                                                                        ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:241: error: illegal start of expression
            Configuration.setDebugStreamConsumer((logMessage) ->
                                                               ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:242: error: illegal start of expression
            {
            ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:242: error: ';' expected
            {
             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:243: error: illegal start of expression
                logMessage = logMessage.trim().replaceAll("[\\r\\n]", "");
                           ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:243: error: ';' expected
                logMessage = logMessage.trim().replaceAll("[\\r\\n]", "");
                                       ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:249: error: illegal start of type
            });
             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:251: error: <identifier> expected
            Logger.info("LWJGL version " + Version.getVersion() + " is initialised");
                       ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:251: error: illegal start of type
            Logger.info("LWJGL version " + Version.getVersion() + " is initialised");
                        ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:251: error: ')' expected
            Logger.info("LWJGL version " + Version.getVersion() + " is initialised");
                                        ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:251: error: ';' expected
            Logger.info("LWJGL version " + Version.getVersion() + " is initialised");
                                          ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:251: error: illegal start of type
            Logger.info("LWJGL version " + Version.getVersion() + " is initialised");
                                                  ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:251: error: ';' expected
            Logger.info("LWJGL version " + Version.getVersion() + " is initialised");
                                                               ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:254: error: illegal start of type
            if (!GLFW3.init())
            ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:254: error: illegal start of type
            if (!GLFW3.init())
                ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:254: error: ')' expected
            if (!GLFW3.init())
                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:254: error: ';' expected
            if (!GLFW3.init())
                      ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:254: error: invalid method declaration; return type required
            if (!GLFW3.init())
                       ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:254: error: ';' expected
            if (!GLFW3.init())
                             ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:258: error: <identifier> expected
            Display.setSize(800, 600);
                           ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:258: error: illegal start of type
            Display.setSize(800, 600);
                            ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:258: error: illegal start of type
            Display.setSize(800, 600);
                                 ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:259: error: <identifier> expected
            Display.centerOnScreen();
                                  ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:262: error: invalid method declaration; return type required
            preInit();
            ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:265: error: <identifier> expected
            SilenceEngine.getInstance().init();
                                     ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:265: error: ';' expected
            SilenceEngine.getInstance().init();
                                       ^
    C:\Users\Wout\projects\SilenceEngine\src\main\java\com\shc\silenceengine\core\Game.java:268: error: <identifier> expected
            Logger.info("Initializing the Game resources");
                       ^
    100 errors

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileJava'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by sriharshachilakapati** [comment]
That means that you are not using JDK 8 to build the project. Try running

```bash
javac -version
```

to verify whether you had a Java 8 `javac` which can compile the project.

**Comment by wb9688** [comment]
I'm using Java 8, because the ouput of `javac -version` is `javac 1.8.0_60`

**Comment by sriharshachilakapati** [comment]
What is the contents of the `JAVA_HOME` environment variable? I don't see any issues in the build scripts.

**Comment by wb9688** [comment]
After a reboot it works...
