### ISSUE TITLE
Entity2D(Polygon) constructor crashes, because Sprite.EMPTY is null.

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [sriharshachilakapati/SilenceEngine#56]
As the title says. I would have changed it myself, but I wasn't sure what would make most sense as an empty value.

**Comment by sriharshachilakapati** [comment]
Weird, can you post the exception? I mean, it just works fine in my game.

**Comment by TheOnlySilverClaw** [comment]
Exception in thread "main" java.lang.NullPointerException
	at com.shc.silenceengine.scene.entity.Entity2D.<init>(Entity2D.java:106)
	at com.shc.silenceengine.scene.entity.Entity2D.<init>(Entity2D.java:95)
	at game.worldmap.entities.EntityArmy.<init>(EntityArmy.java:18)
	at game.worldmap.entities.EntityArmy.<init>(EntityArmy.java:13)
	at game.NewEraGame.<init>(NewEraGame.java:30)
	at main.Start.main(Start.java:23)

**Comment by sriharshachilakapati** [comment]
Aren't you using the `GraphicsEngine` class? It is initialized there.

```java
Sprite.EMPTY = new Sprite(Texture.EMPTY);
```

**Comment by TheOnlySilverClaw** [comment]
*sigh* No, I did not...I mean, your class structure does not tell me anything about what depends on what without looking though all the source code and your Wiki says we should not use the engines directly.
Actually, I cannot find anything that tells me to use it. Where should look?

**Comment by sriharshachilakapati** [comment]
The issue here is the requirement on Texture in the Sprite, which only get's valid after initialization of the GraphicsEngine. So we create the display and context first, and initialize the `Sprite.EMPTY` and `Texture.EMPTY` after that. I'll have to add it to the wiki.

**Comment by TheOnlySilverClaw** [comment]
Okay, fine for me.
