### ISSUE TITLE
Input begin/end Frame is being called in the game loops while silenceengine polls calls them already

### ISSUE THREAD

**Issue by lclc98** [sriharshachilakapati/SilenceEngine#57]
They are being called https://github.com/sriharshachilakapati/SilenceEngine/blob/master/src/main/java/com/shc/silenceengine/core/gameloops/FixedCatchingUpGameLoop.java#L141-L153 
and are called in SilenceEngine
https://github.com/sriharshachilakapati/SilenceEngine/blob/master/src/main/java/com/shc/silenceengine/core/SilenceEngine.java#L133-L144

**Comment by sriharshachilakapati** [comment]
This is not an issue, that is done just to make sure that input is polled at a faster rate, to prevent the feel to the user that input is lagging.

**Comment by lclc98** [comment]
I feel like that shouldn't be an issue unless the users fps is low

**Comment by sriharshachilakapati** [comment]
It is dependent on UPS and not FPS, which almost never goes down the target on modern systems. There is no need to consider the legacy systems because they won't be supporting OpenGL 3.3.

**Comment by sriharshachilakapati** [comment]
Closing because not an issue really.
