### ISSUE TITLE
SilenceException cannot open window on Windows_64 bit.

### ISSUE THREAD

**Issue by speakeasy** [sriharshachilakapati/SilenceEngine#63]
Hi, I was trying to run Blox, however there seems to be an issue opening the window on windows 64bit in netbeans. I also tried in the command prompt and got the same error as with trying to run the test classes in netbeans for the Silence Engine. I am wanting to make a game and I like the SilenceEngine it seems to be most of what I'm looking for in a java game engine aside from the issues of it not opening the first window.

My system is i3, 6gb ram, windows professional 64 bits. I have Netbeans 8.0.2 with the latest Java 8 u72 JDK and JRE installed. I will try downloading LWJGL latest release and natives to see if that helps any. I will also try installing the gradle plugin on netbeans in windows, I had tried it in linux earlier today as I have a dual boot system, however I see the same error.

```
[INFO 01/27/2016 9:22:47 AM] Initializing SilenceEngine. Platform identified as WINDOWS_64
[TRACE 01/27/2016 9:22:47 AM]
com.shc.silenceengine.core.SilenceException: java.lang.RuntimeException: Cannot create window
	at com.shc.silenceengine.core.glfw.Window.<init>(Window.java:280)
	at com.shc.silenceengine.core.glfw.Window.<init>(Window.java:228)
	at com.shc.silenceengine.core.Display.createWindow(Display.java:107)
	at com.shc.silenceengine.core.Display.create(Display.java:83)
	at com.shc.silenceengine.graphics.GraphicsEngine.init(GraphicsEngine.java:73)
	at com.shc.silenceengine.core.SilenceEngine.init(SilenceEngine.java:114)
	at com.shc.silenceengine.core.Game.start(Game.java:265)
	at com.shc.blox.Blox.main(Blox.java:21)

	at com.shc.silenceengine.core.SilenceException.reThrow(SilenceException.java:73)
	at com.shc.silenceengine.core.SilenceEngine.lambda$static$63(SilenceEngine.java:178)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)
```

**Comment by sriharshachilakapati** [comment]
It might mean that your system does not meet the OpenGL context that SilenceEngine needs. What is your GPU? Have you installed the latest drivers for your GPU? SilenceEngine targets OpenGL 3.3 in core profile.

**Comment by speakeasy** [comment]
My GPU is an i5-2450M Intel® HD Graphics 3000, it appears that my graphics drivers are outdated on windows they currently support GL 3.1. I will see if updating the drivers fixes this. There are new intel GL 4.3 drivers out they will take an hour or two to download on this slow connection (It took 30 minutes to download gradle lol)

**Comment by speakeasy** [comment]
Unfortunately on Windows the Intel HD 3000 graphics only support GL 3.1, however on Linux and OSX it supports GL 3.3. Is there any chance of coding in some backwards compatibility to support GL 3.1 on windows? I know a lot of machines on windows are relying on the GL 3.1 when intel could support 3.3 but is lacking in such support.

**Comment by sriharshachilakapati** [comment]
I don't think back porting is going to happen, using modern OpenGL is one of the features of SilenceEngine, and I'm not ready to remove a feature. The shaders are written to use version 330 for GLSL and uses layout qualifier. I'm also planning to use instanced rendering, a feature which is GL 3.3+ only.

Also I strongly think you should upgrade the GPU, because according to the recent Steam hardware survey, more than 90% of people are having OpenGL 3.3 or higher and more than 48% are having access to GL 4.X.

I'm sorry to say that this will not be done.

**Comment by speakeasy** [comment]
I appreciate the information. I understand that it won't be supported and why. I will argue with intel about updating the drivers while I look into how I'm going to afford a new laptop. Thanks.
