### ISSUE TITLE
OpenAL Binding changes

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#67]
Not relevent at the moment but the OpenAL bindings have changed in the newer nightly versions of LWJGL 3 where the ALContext and ALDevice classes are now gone.

**Comment by sriharshachilakapati** [comment]
Yeah I have noticed these changes. The plan is to work on them in the 1.0.1 branch from now on, and stop the current implementation. The new version will be supporting multiple targets too. I have no plans on maintaining the current version in the master, but pull requests are welcome.

**Comment by sriharshachilakapati** [comment]
These changes are solved in the 1.0.1 branch now. Closing this issue.
