### ISSUE TITLE
suggestion preInit Method

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#7]
A preInit method that can be used to resize the display rename it and configure other parts of the engine before it fully start would be a good addition. With it the window wouldn't flash onscreen for a little and then resize itself to the proper size as it would be created as the proper size or resized before it is even displayed. Config options could also be loaded here as they don't normally need any part of the engine started to work properly

EDIT: I changed almost the whole thing as i though of a better way to say it -_-

**Comment by Gamefreak0** [comment]
This isn't a bad idea but right now we're in a [Feature Freeze](http://en.wikipedia.org/wiki/Freeze_%28software_engineering%29), so we might wait to implement this until the next version.

**Comment by ShadowLordAlpha** [comment]
That's fine its just an idea you guys can do if you want

**Comment by ShadowLordAlpha** [comment]
Just another thing that it would fix (well its not really broken in the first place) but you could tell the engine what resources to load in the preInit and it would be able to load them and display your splash screen (you should make it boarder-less and probably smaller too) before you create the main Display. You could also just not make the main display viable until after the init method finishes running and it would have mostly the same effect.

**Comment by sriharshachilakapati** [comment]
This is a really good idea, adding `preInit` can be simple enough. We will be adding this to 0.0.4a version. Thanks for your suggestion. What do you mean by making it border-less? You mean removing the window frame? If that is the case, I can add a new property called `GLFW_DECORATED` to the Display, but not until we have made a 0.0.3a release.

**Comment by ShadowLordAlpha** [comment]
Ya for the splash screen because you already can't close out of that window so making it undecorated is normally a good idea. If you also do it for the whole display class you can also then have a Boarderless windowed mode

**Comment by sriharshachilakapati** [comment]
That's definitely a good idea. Have my word that it will be implemented in 0.0.4a version. Thanks for your suggestion.

**Comment by sriharshachilakapati** [comment]
I have implemented the `preInit()` method, and also added the decorated property to the `Display`. The `preInit()` method is invoked immediately after the LWJGL natives are loaded. I didn't set the decoration to false when invoking the ResourceLoader, but it is doable by the user.

```java
@Override
public void preInit()
{
    // Do whatever you want to do here.
}
```

However, do note that there will be no OpenGL context active here, as this is run before the `GraphicsEngine` is created, which manages the display. I'm now closing this issue, but feel free to comment your thoughts on it.

**Comment by ShadowLordAlpha** [comment]
I known the graphics engine controls the display but it should be possible to use the preinit to set the values in the display as those do not actually need a window or a graphics context to be set properly as they are just numbers until a window is created in the graphics engine

**Comment by sriharshachilakapati** [comment]
Those properties of display ate not just numbers, those setter methods destroy the display and recreate it. Maybe we should make the resource loader is it's own window directly and open the display after everything loads.

**Comment by sriharshachilakapati** [comment]
Update: The preInit method can now be used to set the display properties before the display is created.
