### ISSUE TITLE
Add AZERTY/QWERTY/... (and more) management for Keyboard

### ISSUE THREAD

**Issue by beaucoralk** [sriharshachilakapati/SilenceEngine#70]
I think it would be interesting to add a system to manage different type of keyboard, for example already started QWERTY / AZERTY.

From what I've seen in my tests with LWJGL3, the default keys using the positioning of QWERTY keyboards, it would be interesting to create classes that inherit Keyboard to manage different mode.

I will take time in the weekend I think to do that and you pousez in "merge request" a few things.

If you have some things added to it where a more precise idea of how to do it let me know here.

**Comment by sriharshachilakapati** [comment]
While this would certainly be an interesting feature, it is not possible with current targets, both LWJGL and GWT will not tell you the keyboard layout at runtime, without which this feature is useful. What we can do instead is to allow the game developer to ask for key bindings at the runtime, and let's provide the necessary callbacks that gives them the keycode that was pressed.
