### ISSUE TITLE
Streams support

### ISSUE THREAD

**Issue by sriharshachilakapati** [sriharshachilakapati/SilenceEngine#73]
Since the GWT backend doesn't support Java 8 streams, I'm considering to add https://github.com/aNNiMON/Lightweight-Stream-API as a dependency. What do you think?

**Comment by fseemann** [comment]
Looks like GWT 2.8.0 will support Java 8 syntax and hopefully Steam-API with it. They already provide a beta version of it. See here: [http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_0_BETA1](url). Have'nt looked too far into it though.

**Comment by sriharshachilakapati** [comment]
@fseemann

I'm already using the beta GWT 2.8.0 compiler. I've got into contact with the GWT guys and they said that streams will come in beta 2.

This issue is for support till then. Thanks for looking for it.

**Comment by sriharshachilakapati** [comment]
There is now an android backend too, and it also lacks Java 8 support. So I had to include Retrolambda (only for the android target) and Light weight Streams API for all the targets. This is now solved.
