### ISSUE TITLE
Source and Javadocs not available

### ISSUE THREAD

**Issue by darkhax** [sriharshachilakapati/SilenceEngine#80]
I have only confirmed this in the eclipse setup, however it likely effects IDEA as well. The sources and Javadocs are not automatically applied to the silence engine jars. While this can be solved by downloading/finding them yourself and binding them manually, it seems like something that should be handled by the project creator.

**Comment by sriharshachilakapati** [comment]
Closing this as this is more suited to be present on the Project Creator repository. Opened it as a new issue there: [SEProjectCreator#1](https://github.com/sriharshachilakapati/SEProjectCreator/issues/1)
