### ISSUE TITLE
There are any screen of the game editor?

### ISSUE THREAD

**Issue by RealAquilus** [sriharshachilakapati/SilenceEngine#81]
I want to see how is the Editor previus to start compiling and using it, there are any screen :C ? Thanks

**Comment by darkhax** [comment]
I don't believe there is an editor for the silence engine. Or at least none that I have seen. I have been using Silence on and off for about a year, and it is all hands on.

**Comment by sriharshachilakapati** [comment]
Yes, there is no editor for SilenceEngine. There is a project creation tool however to assist you in creating cross platform project using gradle.
