### ISSUE TITLE
Bug: Splash Screen not closing

### ISSUE THREAD

**Issue by ShadowLordAlpha** [sriharshachilakapati/SilenceEngine#9]
After calling `ResourceLoader.startLoading();` two times the whole engine seems to lock up and not move on past the Splash Screen.
Code:

```java
Logger.log("Loading Resources");
ResourceLoader loader = ResourceLoader.getInstance();
// some random font I have that loads fine
int fontID = loader.defineFont("Resources/Fonts/OpenSans-Regular.ttf", TrueTypeFont.STYLE_NORMAL, 24);
		
loader.startLoading();
Fonts.OPEN_SANS = loader.getFont(fontID);
loader.startLoading();
Logger.log("Setting up Display");
Display.setTitle("Break the Engine :D");
Display.centerOnScreen();

SilenceEngine.graphics.setClearColor(Color.WHITE_SMOKE);
```

Adding a boolean that stops the SplashScreen from displaying more than once would probably fix the problem as well as allow for loading other objects using the your normal method possibly in another thread :D.

**Comment by sriharshachilakapati** [comment]
You are not assumed to call the `startLoading` method more than once before calling the `clear` method. Why are you trying to start it again? The loading screen is not the splash screen. If you want to render something other than the default screen, you can render your own progress bar by setting a callback.

```java
loader.setRenderProgressCallback(this::myRenderProgressCallback);

private void myRenderProgressCallback(Batcher batcher, float percentage, String file)
{
    // Render your progress bar here.
}
```

The callback will be called once for each file is loaded and the percentage is calculated. If you want to load the resources in between a game, you can always clear the loader and start loading again.

**Comment by ShadowLordAlpha** [comment]
"You are not assumed"
Never a good idea to assume anything. (also that loading screen is a splash screen as its displayed as a visual representation of the game loading and doing stuff before the game is actually usable though they technically are the same thing here). If you don't wish for someone to call it before they call a `clear()` then you should make that part of the code so that it can't be done before they call `clear()` as it locks up your engine and that happening for any reason is bad

**Comment by sriharshachilakapati** [comment]
That callback exists to allow the user to do his own rendering of the progress bar and the loading screen. I'm not sure that I understood your point better, can you re-phrase it for me? I think there is something issue that I may not have seen in it, I'll run a thorough check in a few days (I'm participating in LD this time).

**Comment by ShadowLordAlpha** [comment]
The bug as I'm calling it is the loading screen locks the entire engine up when called twice without a clear. Because you said its nat a manager though it does have parts of a manager you could fix it with one line and remove the need for the user to clear it themselves by adding in a `clear()` to the very beginning of the `startLoading()` code I haven't test the proper way using clear yet but I'm assuming it works so this way would fix the loading screen locking the engine and keep the same functionality

**Comment by ShadowLordAlpha** [comment]
Also with this if you give it nothing to load it gives a `java.lang.ArithmeticException: / by zero` I know its not the proper way but the program should just ignore the load if there is nothing to load and not give the error with something in the javadocs stating that it will do so or make it throw a different exception idk

**Comment by sriharshachilakapati** [comment]
Thanks for reporting that. I will look into this, and fix it as soon as possible. Also I noticed the issue that was causing the engine to hang when the resource loader is started the second time.

The reason is the private variable `renderedProgress` not being reset to 0, and then the render loop of the default callback will be doing on repeatedly rendering the same progress making it look it ceased execution.

I'll fix it as soon as possible. Thanks a lot for submitting the issue.

**Comment by ShadowLordAlpha** [comment]
Just another thing but could you also make it so that when loading a resource it doesn't use the class loader as if i remember properly that looks inside the jar and (again) in larger games you don't want the jar to hold all your resources though I could be totaly wrong about it. maybe make it use the relitive paths for the loader and main way of loading things for the next version? though if it was added as a side part that would be fine as well.

**Comment by sriharshachilakapati** [comment]
I just pushed a commit which fixes this bug. The snippet you provided now works as expected. Thanks a lot for reporting the issue. Coming to the second comment, passing strings will also work for files stored external to the JAR. But yeah, passing a `File` could be done. I'll add that in 0.0.4a release.
